#!/bin/bash -l

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

SKIP=/var/lib/prometheus/.BACKUP_SKIP
PRISTINE=/var/lib/prometheus/PRISTINE

cleanup() {
  echo "Starting Prometheus"

  systemctl stop lighttpd

  touch $SKIP
  systemctl start prometheus
  rm -f $SKIP
}

save() {
  if [ "$SYSTEMD_JOB" == "true" ] && [ -r $SKIP ]; then
    exit 0
  fi

  # Ensures we start prometheus no matter what once done
  if [ "$SYSTEMD_JOB" == "" ]; then
    trap cleanup EXIT

    # Prometheus backs itself up after stopping
    systemctl stop prometheus

    # Prometheus was running, it will call us back once it's done.
    if [ "$?" == "0" ]; then
      exit 0
    fi
  fi

  # We are now stopped so bring up our Backup Running page
  systemctl start lighttpd

  # Backup
  run_duply prometheus backup --force --allow-source-mismatch
}

restore() {
  if [ "$SYSTEMD_JOB" == "true" ] && [ -r $SKIP ]; then
    exit 0
  fi

  if [ "$SYSTEMD_JOB" == "" ]; then
    touch $SKIP
    systemctl stop prometheus
    rm -f $SKIP
  fi

  # We are now stopped so bring up our Backup Running page
  systemctl start lighttpd

  # Clean out Prometheus
  rm -rf /var/lib/prometheus/*

  # Recover
  run_duply prometheus restore /var/lib/prometheus --force

  # Cleanup just to be certain
  rm -f $PRISTINE

  exit 0
}

purge() {
  # Cleanup and expire backups
  run_duply prometheus purge_cleanup  --force
}

# We run duply under an exclusive lock, to avoid parallel execution
# shellcheck disable=SC2094
run_duply() {
  (
    flock -x 9
    /usr/local/bin/duply "$@"
  ) 9< /usr/local/bin/duply
}

case "$1" in
   save)
   save
   ;;
   restore)
   restore
   ;;
   purge)
   purge
   ;;
   *)
   echo "$0 [save|restore]"
   exit
   ;;
esac

